/* Generated by Yosys 0.30+48 (git sha1 b5b0b7e83, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "counter.v:1.1-37.10" *)
module Counter(clk, reset_n, count_to, count_inc, count_dec, load_en, flag_count_max, flag_count_min);
  (* src = "counter.v:32.3-35.6" *)
  wire _000_;
  (* src = "counter.v:32.3-35.6" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  (* src = "counter.v:2.14-2.17" *)
  input clk;
  wire clk;
  (* src = "counter.v:6.14-6.23" *)
  input count_dec;
  wire count_dec;
  (* src = "counter.v:5.14-5.23" *)
  input count_inc;
  wire count_inc;
  (* src = "counter.v:13.13-13.22" *)
  wire [3:0] count_max;
  (* src = "counter.v:4.20-4.28" *)
  input [3:0] count_to;
  wire [3:0] count_to;
  (* src = "counter.v:12.13-12.20" *)
  wire [3:0] counter;
  (* src = "counter.v:8.14-8.28" *)
  output flag_count_max;
  wire flag_count_max;
  (* src = "counter.v:9.14-9.28" *)
  output flag_count_min;
  wire flag_count_min;
  (* src = "counter.v:7.14-7.21" *)
  input load_en;
  wire load_en;
  (* src = "counter.v:3.14-3.21" *)
  input reset_n;
  wire reset_n;
  dti_55g_10t_invx1 _056_ (
    .A(count_dec),
    .Z(_010_)
  );
  dti_55g_10t_invx1 _057_ (
    .A(counter[0]),
    .Z(_011_)
  );
  dti_55g_10t_invx1 _058_ (
    .A(counter[2]),
    .Z(_012_)
  );
  dti_55g_10t_xor2x1 _059_ (
    .A(count_max[1]),
    .B(counter[1]),
    .Z(_013_)
  );
  dti_55g_10t_xor2x1 _060_ (
    .A(count_max[0]),
    .B(counter[0]),
    .Z(_014_)
  );
  dti_55g_10t_xor2x1 _061_ (
    .A(count_max[3]),
    .B(counter[3]),
    .Z(_015_)
  );
  dti_55g_10t_xor2x1 _062_ (
    .A(count_max[2]),
    .B(counter[2]),
    .Z(_016_)
  );
  dti_55g_10t_or3x1 _063_ (
    .A(_013_),
    .B(_014_),
    .C(_016_),
    .Z(_017_)
  );
  dti_55g_10t_nor2x1 _064_ (
    .A(_015_),
    .B(_017_),
    .Z(_000_)
  );
  dti_55g_10t_or2x1 _065_ (
    .A(counter[0]),
    .B(counter[1]),
    .Z(_018_)
  );
  dti_55g_10t_nor3x1 _066_ (
    .A(counter[2]),
    .B(counter[3]),
    .C(_018_),
    .Z(_001_)
  );
  dti_55g_10t_and2x1 _067_ (
    .A(load_en),
    .B(reset_n),
    .Z(_019_)
  );
  dti_55g_10t_nand2x1 _068_ (
    .A(load_en),
    .B(reset_n),
    .Z(_020_)
  );
  dti_55g_10t_nand2x1 _069_ (
    .A(count_max[0]),
    .B(_020_),
    .Z(_021_)
  );
  dti_55g_10t_nand2x1 _070_ (
    .A(count_to[0]),
    .B(_019_),
    .Z(_022_)
  );
  dti_55g_10t_nand2x1 _071_ (
    .A(_021_),
    .B(_022_),
    .Z(_002_)
  );
  dti_55g_10t_nand2x1 _072_ (
    .A(count_max[1]),
    .B(_020_),
    .Z(_023_)
  );
  dti_55g_10t_nand2x1 _073_ (
    .A(count_to[1]),
    .B(_019_),
    .Z(_024_)
  );
  dti_55g_10t_nand2x1 _074_ (
    .A(_023_),
    .B(_024_),
    .Z(_003_)
  );
  dti_55g_10t_nand2x1 _075_ (
    .A(count_max[2]),
    .B(_020_),
    .Z(_025_)
  );
  dti_55g_10t_nand2x1 _076_ (
    .A(count_to[2]),
    .B(_019_),
    .Z(_026_)
  );
  dti_55g_10t_nand2x1 _077_ (
    .A(_025_),
    .B(_026_),
    .Z(_004_)
  );
  dti_55g_10t_nand2x1 _078_ (
    .A(count_max[3]),
    .B(_020_),
    .Z(_027_)
  );
  dti_55g_10t_nand2x1 _079_ (
    .A(count_to[3]),
    .B(_019_),
    .Z(_028_)
  );
  dti_55g_10t_nand2x1 _080_ (
    .A(_027_),
    .B(_028_),
    .Z(_005_)
  );
  dti_55g_10t_and2x1 _081_ (
    .A(count_inc),
    .B(_010_),
    .Z(_029_)
  );
  dti_55g_10t_nand2x1 _082_ (
    .A(count_inc),
    .B(_010_),
    .Z(_030_)
  );
  dti_55g_10t_nor2x1 _083_ (
    .A(_000_),
    .B(_030_),
    .Z(_031_)
  );
  dti_55g_10t_nor3x1 _084_ (
    .A(count_inc),
    .B(_010_),
    .C(_001_),
    .Z(_032_)
  );
  dti_55g_10t_nor3x1 _085_ (
    .A(load_en),
    .B(_031_),
    .C(_032_),
    .Z(_033_)
  );
  dti_55g_10t_nand2x1 _086_ (
    .A(counter[0]),
    .B(_033_),
    .Z(_034_)
  );
  dti_55g_10t_nor2x1 _087_ (
    .A(load_en),
    .B(_033_),
    .Z(_035_)
  );
  dti_55g_10t_nand2x1 _088_ (
    .A(_011_),
    .B(_035_),
    .Z(_036_)
  );
  dti_55g_10t_nand2x1 _089_ (
    .A(_034_),
    .B(_036_),
    .Z(_006_)
  );
  dti_55g_10t_nand2x1 _090_ (
    .A(counter[1]),
    .B(_033_),
    .Z(_037_)
  );
  dti_55g_10t_nand2x1 _091_ (
    .A(counter[1]),
    .B(_030_),
    .Z(_038_)
  );
  dti_55g_10t_xor2x1 _092_ (
    .A(counter[1]),
    .B(_029_),
    .Z(_039_)
  );
  dti_55g_10t_nand2x1 _093_ (
    .A(_011_),
    .B(_039_),
    .Z(_040_)
  );
  dti_55g_10t_or2x1 _094_ (
    .A(_011_),
    .B(_039_),
    .Z(_041_)
  );
  dti_55g_10t_nand3x1 _095_ (
    .A(_035_),
    .B(_040_),
    .C(_041_),
    .Z(_042_)
  );
  dti_55g_10t_nand2x1 _096_ (
    .A(_037_),
    .B(_042_),
    .Z(_007_)
  );
  dti_55g_10t_nand2x1 _097_ (
    .A(counter[2]),
    .B(_033_),
    .Z(_043_)
  );
  dti_55g_10t_nand2x1 _098_ (
    .A(_038_),
    .B(_041_),
    .Z(_044_)
  );
  dti_55g_10t_nor2x1 _099_ (
    .A(_012_),
    .B(_030_),
    .Z(_045_)
  );
  dti_55g_10t_nor2x1 _100_ (
    .A(counter[2]),
    .B(_029_),
    .Z(_046_)
  );
  dti_55g_10t_or2x1 _101_ (
    .A(_045_),
    .B(_046_),
    .Z(_047_)
  );
  dti_55g_10t_xor2x1 _102_ (
    .A(_044_),
    .B(_047_),
    .Z(_048_)
  );
  dti_55g_10t_nand2x1 _103_ (
    .A(_035_),
    .B(_048_),
    .Z(_049_)
  );
  dti_55g_10t_nand2x1 _104_ (
    .A(_043_),
    .B(_049_),
    .Z(_008_)
  );
  dti_55g_10t_nor3x1 _105_ (
    .A(_012_),
    .B(_030_),
    .C(_041_),
    .Z(_050_)
  );
  dti_55g_10t_and3x1 _106_ (
    .A(_038_),
    .B(_041_),
    .C(_046_),
    .Z(_051_)
  );
  dti_55g_10t_nor2x1 _107_ (
    .A(_050_),
    .B(_051_),
    .Z(_052_)
  );
  dti_55g_10t_nor2x1 _108_ (
    .A(_033_),
    .B(_052_),
    .Z(_053_)
  );
  dti_55g_10t_and2x1 _109_ (
    .A(counter[3]),
    .B(_053_),
    .Z(_054_)
  );
  dti_55g_10t_nor2x1 _110_ (
    .A(counter[3]),
    .B(_053_),
    .Z(_055_)
  );
  dti_55g_10t_nor3x1 _111_ (
    .A(load_en),
    .B(_054_),
    .C(_055_),
    .Z(_009_)
  );
  (* src = "counter.v:15.3-30.6" *)
  dti_55g_10t_ffqbcka01x1 _112_ (
    .CK(clk),
    .D(_002_),
    .Q(count_max[0]),
    .RN(1'h1)
  );
  (* src = "counter.v:15.3-30.6" *)
  dti_55g_10t_ffqbcka01x1 _113_ (
    .CK(clk),
    .D(_003_),
    .Q(count_max[1]),
    .RN(1'h1)
  );
  (* src = "counter.v:15.3-30.6" *)
  dti_55g_10t_ffqbcka01x1 _114_ (
    .CK(clk),
    .D(_004_),
    .Q(count_max[2]),
    .RN(1'h1)
  );
  (* src = "counter.v:15.3-30.6" *)
  dti_55g_10t_ffqbcka01x1 _115_ (
    .CK(clk),
    .D(_005_),
    .Q(count_max[3]),
    .RN(1'h1)
  );
  (* src = "counter.v:32.3-35.6" *)
  dti_55g_10t_ffqbcka01x1 _116_ (
    .CK(clk),
    .D(_000_),
    .Q(flag_count_max),
    .RN(1'h1)
  );
  (* src = "counter.v:32.3-35.6" *)
  dti_55g_10t_ffqbcka01x1 _117_ (
    .CK(clk),
    .D(_001_),
    .Q(flag_count_min),
    .RN(1'h1)
  );
  (* src = "counter.v:15.3-30.6" *)
  dti_55g_10t_ffqbcka01x1 _118_ (
    .CK(clk),
    .D(_006_),
    .Q(counter[0]),
    .RN(reset_n)
  );
  (* src = "counter.v:15.3-30.6" *)
  dti_55g_10t_ffqbcka01x1 _119_ (
    .CK(clk),
    .D(_007_),
    .Q(counter[1]),
    .RN(reset_n)
  );
  (* src = "counter.v:15.3-30.6" *)
  dti_55g_10t_ffqbcka01x1 _120_ (
    .CK(clk),
    .D(_008_),
    .Q(counter[2]),
    .RN(reset_n)
  );
  (* src = "counter.v:15.3-30.6" *)
  dti_55g_10t_ffqbcka01x1 _121_ (
    .CK(clk),
    .D(_009_),
    .Q(counter[3]),
    .RN(reset_n)
  );
endmodule
